spring.application.name=taxistfg

# Configuracion de la base de datos
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mcastillol14_taxi}
spring.datasource.username=${DB_USERNAME:alumno}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Clave de firma JWT (debe ser una cadena Base64 de al menos 256 bits)
jwt.secret=${JWT_SECRET}

# Configuracion de Thymeleaf (opcional si usas Thymeleaf por defecto)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

logging.level.web=trace

# Configuracion del servidor (puedes personalizar el puerto y mas)
server.port=8080
server.servlet.context-path=/

# Salida en consola con colores (para facilitar la lectura)
spring.output.ansi.enabled=always

# Configuracion de logs (opcional, solo para mas control de los logs en consola)
logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.luxeride.taxistfg=DEBUG

# Configuracion libreria gmail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




